#include <iostream>
using namespace std;
int main(){
    cout << "Hey! Would you like to learn about calculating GDP?\n(y/n):";
    char input;
    int gdp;
    cin >> input;
    cout << endl;
    if (input=='y'){
        cout << "Do you know there are two methods of calculating GDP?" << endl;
        cout << "1. Expenditure Approach" << endl;
        cout << "2. Income Approach" << endl;
        cout << "What method would you like to learn?\n(1/2):";
        cin >> input;
        cout << endl;
        if (input=='1'){
            int c, g, i, nx;
            cout << "The expenditure approach is the most commonly used GDP formula, which is based on the money spent by various groups that participate in the economy." << endl;
            cout << "GDP = C + G + I + NX" << endl;
            cout << "C is consumption. Enter the value of C: " << endl;
            cin >> c;
            cout << "G is total government expenditures. Enter the value of G: " << endl;
            cin >> g;
            cout << "I is sum of a country\'s investments. Enter the value of I: " << endl;
            cin >> i;
            cout << "NX is net exports. Enter the value of NX: " << endl;
            cin >> nx;
            cout << endl;
            gdp = c + g + i + nx;
            cout << "You have entered all the values required to calculate GDP using Expenditure method.\nNow, we will add all of them and get a total of " << gdp << ".\nAnd this is the value of GDP." << endl;
        }
        else if (input=='2'){
            int tni, st, d, nffi;
            cout << "This GDP formula takes the total income generated by the goods and services produced." << endl;
            cout << "GDP = TNI + ST + D + NFFI" << endl;
            cout << "TNI is Total National Income. Enter the value of TNI: " << endl;
            cin >> tni;
            cout << "ST is Sales Taxes. Enter the value of ST: " << endl;
            cin >> st;
            cout << "D is Depreciation. Enter the value of D: " << endl;
            cin >> d;
            cout << "NFFI is Net Foreign Factor Income. Enter the value of NFFI: " << endl;
            cin >> nffi;
            cout << endl;
            gdp = tni + st + d + nffi;
            cout << "You have entered all the values required to calculate GDP using Income method.\nNow, we will add all of them and get a total of " << gdp << ".\nAnd this is the value of GDP." << endl;
        }
        else{
            cout << "Your input was not a valid entry." << endl;
        }
    }
    else if(input=='n'){
        cout << "Sorry! But you are so boring.\nBye" << endl;
    }
    else{
            cout << "Your input was not a valid entry." << endl;
        }
    return 0;
}
